---
- hosts: www

  vars:
    - root_dir: "{{ playbook_dir }}"
    - my_domains:
      - {
          names:        "voronenko.net www.voronenko.net",
          nginx_config: "/etc/nginx/sites-available/letsencrypt_site_to_validate"
        }

  pre_tasks:
    - debug: msg="Pre tasks section"

  roles:
    - {
        role: "sa-nginx"
      }
    - {
        role:         "sa-include",
        include_file: "{{ root_dir }}/demosite.yml"
      }
    - {
        role:              "sa-lets-encrypt",
        le_domains:        "{{ my_domains }}",
        #le_ca:            "https://acme-staging.api.letsencrypt.org/directory",
        option_run_once:   True,
        option_setup_cron: True
      }

  tasks:
    - debug: msg="Tasks section"
